- name: Hello World Sample
  hosts: loadbalancer
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! LB"
- name: WEB Tasks
  hosts: web
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present
    - name: Enable service httpd, and not touch the state
      service:
        name: httpd
        enabled: yes
